import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// import { } from '@fortawesome/free-regular-svg-icons'

import {
    faPlay,
    faStop,
    faLink,
    faFont,
    faInfoCircle,
    faDownload, 
    faCloudUploadAlt,
    faVideo, 
    faMicrophone, 
    faMicrophoneSlash,
    faFileInvoice, 
    faLayerGroup, 
    faPhotoVideo, 
    faShareAlt, 
    faSortAmountDownAlt, 
    faQuestion, 
    faFileInvoiceDollar, 
    faCreditCard, 
    faImage, 
    faKey, 
    faRedo, 
    faTimes, 
    faPhone, 
    faMapMarkerAlt, 
    faPlus,
    faBell, 
    faClipboardList, 
    faCocktail, 
    faListAlt, 
    faThLarge, 
    faHome, 
    faUser, 
    faUsers, 
    faTachometerAlt, 
    faPencilAlt, 
    faSearch, 
    faCircle, 
    faTrashAlt, 
    faStore, 
    faLock, 
    faSignOutAlt, 
    faCog, 
    faChevronLeft, 
    faChevronRight,
    faChevronUp,
    faChevronDown,
} from '@fortawesome/free-solid-svg-icons'

import {
    faGithub
} from '@fortawesome/free-brands-svg-icons'

import {
    faSave,
    faFile,
    faCheckCircle,
    faCopy,
    faEye
} from '@fortawesome/free-regular-svg-icons'

library.add(
    faFile,
    faSave,
    faPlay,
    faStop,
    faLink,
    faFont,
    faInfoCircle,
    faDownload,
    faCheckCircle,
    faCloudUploadAlt,
    faVideo, 
    faMicrophone, 
    faMicrophoneSlash, 
    faFileInvoice, 
    faLayerGroup, 
    faPhotoVideo, 
    faShareAlt, 
    faSortAmountDownAlt, 
    faQuestion, 
    faFileInvoiceDollar, 
    faCreditCard, 
    faImage, 
    faKey, 
    faRedo, 
    faTimes, 
    faPhone, 
    faMapMarkerAlt, 
    faPlus, 
    faEye, 
    faBell, 
    faClipboardList, 
    faCocktail, 
    faListAlt, 
    faThLarge, 
    faHome, 
    faUser, 
    faUsers, 
    faTachometerAlt, 
    faPencilAlt, 
    faSearch, 
    faCircle, 
    faTrashAlt, 
    faStore, 
    faLock, 
    faSignOutAlt, 
    faCog, 
    faChevronLeft, 
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faGithub,
    faCopy
)

Vue.component('fa', FontAwesomeIcon)
